version: '3'
services:
#  tws:
#    image: algotrader/ibgateway:963
#    environment:
#      # loaded from .env file in same directory
#      TWS_USERNAME: ${TWS_USERNAME}
#      TWS_PASSWORD: ${TWS_PASSWORD}
#      TRADING_MODE: ${TRADING_MODE}
#    ports:
#      - 4001:4001
#    volumes:
#      # loaded from .env file in same directory
#      - ./tws:/var/lib/tws
#
#  Runs the most current stable Interactive Brokers Gateway installer and allows to configure the Gateway settings
#  before committing the configured container.
#  Steps to install and use IB Gateway:
#  Run the container using either:
#  > docker run -e VNC_PASSWORD=your-password -p 5900:5900 sebfia/ib-gateway-stable
#  or
#  > docker-compose build
#  Wait for IB Gateway to start and enter your login credentials
#  Adapt the API settings to your needs.
#  Close IB Gateway which will stop the container and commit the container's state to a new image:
#  docker commit <your-container-name> <your-locally-configured-image-name>
#  Use your configured image for further processing
#  ib-gateway:
#    image: sebfia/ib-gateway-stable:latest


  amq:
    image: vromero/activemq-artemis:2.4.0
    environment:
      ARTEMIS_USERNAME: "admin"
      ARTEMIS_PASSWORD: "admin123"
      ARTEMIS_MIN_MEMORY: "512M"
      ARTEMIS_MAX_MEMORY: "2G"
    volumes:
      - ./amq/jolokia-access.xml:/var/lib/artemis/etc/jolokia-access.xml
    ports:
      - "8161:8161"
      - "61616:61616"
